version: "3.8"

services:
  mysql_container:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql


  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql_container
    environment:
      DB_HOST: mysql_container
      DB_USER: root
      DB_PORT: 3306
      DB_PASS: rootpassword
      DB_NAME: library_db
    command: ["/bin/bash", "-c", "./wait-for-mysql.sh python app.py"]

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask_app

volumes:
  mysql_data: