version: '3.8'

services:
  mysql_container:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./sql_scripts/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
